{ pkgs }:
pkgs.runCommand "fmab-customizations" { } ''
  mkdir -p $out/share/icons
  cp -Lr ${pkgs.kdePackages.breeze-icons}/share/icons/breeze $out/share/icons/fmab
  cp -Lr ${pkgs.kdePackages.breeze-icons}/share/icons/breeze-dark $out/share/icons/fmab-dark
  chmod 644 $out/share/icons/fmab/apps/22/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/apps/22@2x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/apps/22@3x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/apps/24/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/apps/24@2x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/apps/24@3x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/16/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/16/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/16@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/16@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@2x/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/16@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/16@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/16@3x/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/22/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/22/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/22@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/22@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/22@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/22@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/22@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/24/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/24/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/24@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/24@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/24@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/24@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/24@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab/places/32/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/64/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/64/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab/places/96/start-here-kde.svg
  chmod 644 $out/share/icons/fmab/places/96/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/apps/22/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/apps/22@2x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/apps/22@3x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/apps/24/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/apps/24@2x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/apps/24@3x/plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/16/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/16/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@2x/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/16@3x/start-here-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/22/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/22/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/22@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/24/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/24/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@2x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@2x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@2x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@2x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@3x/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@3x/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@3x/start-here-kde-plasma-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/24@3x/start-here-kde-symbolic.svg
  chmod 644 $out/share/icons/fmab-dark/places/32/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/64/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/64/start-here-kde-plasma.svg
  chmod 644 $out/share/icons/fmab-dark/places/96/start-here-kde.svg
  chmod 644 $out/share/icons/fmab-dark/places/96/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/22/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/22@2x/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/22@3x/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/24/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/24@2x/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/apps/24@3x/plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16/start-here-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@2x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@2x/start-here-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@3x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/16@3x/start-here-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@2x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@3x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/22@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@2x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@3x/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/24@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/32/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/64/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/64/start-here-kde-plasma.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/96/start-here-kde.svg
  cp ${../fmab/icons/light.svg} $out/share/icons/fmab/places/96/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/22/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/22@2x/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/22@3x/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/24/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/24@2x/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/apps/24@3x/plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16/start-here-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@2x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@2x/start-here-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@3x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/16@3x/start-here-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@2x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@3x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/22@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@2x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@2x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@2x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@2x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@3x/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@3x/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@3x/start-here-kde-plasma-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/24@3x/start-here-kde-symbolic.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/32/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/64/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/64/start-here-kde-plasma.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/96/start-here-kde.svg
  cp ${../fmab/icons/dark.svg} $out/share/icons/fmab-dark/places/96/start-here-kde-plasma.svg
  cp -r ${../fmab}/* $out/share/
  chmod -R u+w $out/share
  sed -i "s|ImageDir=.*|ImageDir=$out/share/plymouth/themes/fmab|" $out/share/plymouth/themes/fmab/fmab.plymouth
  sed -i "s|ScriptFile=.*|ScriptFile=$out/share/plymouth/themes/fmab/fmab.script|" $out/share/plymouth/themes/fmab/fmab.plymouth
  sed -i "s|logo=.*|logo=$out/share/sddm/themes/fmab/default-logo.svg|" $out/share/sddm/themes/fmab/theme.conf
  sed -i "s|background=.*|background=$out/share/wallpapers/fmab-lock/contents/images/1920x1080.png|" $out/share/sddm/themes/fmab/theme.conf
''
# if icon change is not working, replace ${kdePackages.libplasma}/share/plasma/desktoptheme/*/icons/start.svgz
